### ISSUE TITLE
[MLINKCHECK-3] Cannot add excludedHttpStatusErrors configuration

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-linkcheck-plugin#16]
**[Mike Youngstrom](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=youngm)** opened **[MLINKCHECK-3](https://issues.apache.org/jira/browse/MLINKCHECK-3?redirect=false)** and commented

When I attempt to use excludedHttpStatusErrors like in the following configuration:

    <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-linkcheck-plugin</artifactId>
         <version>1.0.1</version>
         <configuration>
              <excludedHttpStatusErrors>
                       <excludedHttpStatusError>401</excludedHttpStatusError>
              </excludedHttpStatusErrors>
         </configuration>
    </plugin>

With Maven 2.2.1 I get the following exception:

[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] [I cannot be cast to [Ljava.lang.Object;
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.Object;
at org.codehaus.plexus.component.configurator.converters.composite.ArrayConverter.fromConfig
uration(ArrayConverter.java:141)
at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(Comp
onentValueSetter.java:247)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter
.processConfiguration(ObjectWithFieldsConverter.java:137)
at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(
BasicComponentConfigurator.java:56)
at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.ja
va:1357)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:
724)
at org.apache.maven.plugin.DefaultPluginManager.getReport(DefaultPluginManager.java:583)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.j
ava:982)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor
.java:650)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifec
ycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.
java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultL
ifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleE
xecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java
:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 1.0.1

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

Fixed in [r1002087](http://svn.apache.org/viewvc?rev=1002087&view=rev).
1.1-SNAPSHOT is deployed, please test.
