### ISSUE TITLE
[MLINKCHECK-6] IllegalArgumentException for some URIs

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-linkcheck-plugin#26]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** opened **[MLINKCHECK-6](https://issues.apache.org/jira/browse/MLINKCHECK-6?redirect=false)** and commented

This has been reported at MLINKCHECK-4. It only happens when javadocs are checked and some excludedLink pattern contains a * wildcard. The reason is that some published javadoc sites are not valid URIs, eg http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#wait(long, int)

---

**Affects:** 1.0.1

**Attachments:**
- [MLINKCHECK-6.zip](https://issues.apache.org/jira/secure/attachment/12717161/MLINKCHECK-6.zip) (_4.08 kB_)

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

Test project attached. Running site gives the following stacktrace:

```
[ INFO] Begin to check links in files...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
Illegal character in fragment at index 87: http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#wait(long, int)
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.IllegalArgumentException
        at java.net.URI.create(URI.java:842)
        at org.apache.maven.doxia.linkcheck.validation.LinkValidatorManager.matchPattern(LinkValidatorManager.java:414)
        at org.apache.maven.doxia.linkcheck.validation.LinkValidatorManager.validateLink(LinkValidatorManager.java:132)
        at org.apache.maven.doxia.linkcheck.DefaultLinkCheck.check(DefaultLinkCheck.java:558)
        at org.apache.maven.doxia.linkcheck.DefaultLinkCheck.findAndCheckFiles(DefaultLinkCheck.java:480)
        at org.apache.maven.doxia.linkcheck.DefaultLinkCheck.findAndCheckFiles(DefaultLinkCheck.java:439)
        at org.apache.maven.doxia.linkcheck.DefaultLinkCheck.findAndCheckFiles(DefaultLinkCheck.java:439)
        at org.apache.maven.doxia.linkcheck.DefaultLinkCheck.execute(DefaultLinkCheck.java:241)
        at org.apache.maven.plugins.linkcheck.LinkcheckReport.executeLinkCheck(LinkcheckReport.java:512)
        at org.apache.maven.plugins.linkcheck.LinkcheckReport.execute(LinkcheckReport.java:412)
        at org.apache.maven.plugins.linkcheck.LinkcheckReport.executeReport(LinkcheckReport.java:452)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:93)
        at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:164)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:330)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:134)
        at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:158)
        at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:120)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: java.net.URISyntaxException: Illegal character in fragment at index 87: http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#wait(long, int)
        at java.net.URI$Parser.fail(URI.java:2809)
        at java.net.URI$Parser.checkChars(URI.java:2982)
        at java.net.URI$Parser.parse(URI.java:3028)
        at java.net.URI.<init>(URI.java:578)
        at java.net.URI.create(URI.java:840)
        ... 35 more
```

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

Fixed in [r1003039](http://svn.apache.org/viewvc?rev=1003039&view=rev).
